<?php
/* @var $block \Sga\DeveloperToolbar\Block\Toolbar\Layout */
$handles = $block->getHandles();
$blocks = $block->getBlocksByTime();
$blocksNotUsed = $block->getBlocksNotUsed();
?>
<div class="dtt-tabs">
    <ul>
        <li class="dtt-tab" data-tab="#dtt_tab_treeblocks<?= $block->getRequestKey() ?>">Tree Blocks</li>
        <li class="dtt-tab" data-tab="#dtt_tab_blocks<?= $block->getRequestKey() ?>">Blocks (<?= count($blocks) ?>)</li>
        <li class="dtt-tab" data-tab="#dtt_tab_blocks_not_used<?= $block->getRequestKey() ?>">Blocks Not Used (<?= count($blocksNotUsed) ?>)</li>
        <li class="dtt-tab" data-tab="#dtt_tab_handles<?= $block->getRequestKey() ?>">Handles (<?= count($handles) ?>)</li>
        <li class="dtt-tab" data-tab="#dtt_tab_updates_xml<?= $block->getRequestKey() ?>">Updates XML</li>
    </ul>

    <div id="dtt_tab_treeblocks<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-blocks dtt-tree">
        <ul class="actions">
            <li><a href="#" class="open-tree">Open tree</a></li>
            <li><a href="#" class="close-tree">Close tree</a></li>
        </ul>
        <?= $block->getHtmlTreeBlocks() ?>
    </div>

    <div id="dtt_tab_blocks<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-blocks">
        <table class="dtt-table">
            <thead>
            <tr>
                <th>Block</th>
                <th>Time Render (sec)</th>
                <th>Info</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($blocks as $name => $b): ?>
                <tr class="<?= isset($b['time']) ? $block->getColorCss($b['time']) : '' ?>">
                    <td><?= $name ?></td>
                    <td><?= isset($b['time']) ? $b['time'] : '' ?></td>
                    <td>
                        <?= isset($b['identifier']) && $b['identifier'] !== '' ? 'Identifier : '.$b['identifier'].'<br>' : '' ?>
                        <?= isset($b['lifetime']) && $b['lifetime'] !== '' ? 'Lifetime : '.$b['lifetime'].'<br>' : '' ?>
                        <?= isset($b['file']) && $b['file'] !== '' ? 'Template : '.$b['file'].'<br>' : '' ?>
                        <?= isset($b['class_name']) ? 'Class : '.$b['class_name'].'<br>' : '' ?>
                        <?= isset($b['class_file']) ? 'Class File : '.$b['class_file'].'<br>' : '' ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>

    <div id="dtt_tab_blocks_not_used<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-blocks">
        <table class="dtt-table">
            <thead>
            <tr>
                <th>Block</th>
                <th>Info</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($blocksNotUsed as $name => $b): ?>
                <tr>
                    <td><?= $name ?></td>
                    <td>
                        <?= isset($b['file']) ? 'Template : '.$b['file'].'<br>' : '' ?>
                        <?= isset($b['class_name']) ? 'Class : '.$b['class_name'].'<br>' : '' ?>
                        <?= isset($b['class_file']) ? 'Class : '.$b['class_file'].'<br>' : '' ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>

    <div id="dtt_tab_handles<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-handles">
        <ul>
            <?php foreach ($handles as $handle): ?>
                <?php $handleFiles = $block->getHandleInformations($handle) ?>
                <li>
                    <span class="handle open-children"><?= $handle ?></span>
                    <?php if (count($handleFiles) > 0) : ?>
                    <ul class="children" style="display:none">
                        <?php foreach ($handleFiles as $handleFile): ?>
                        <li>
                            <span class="file open-children"><?= $block->getHandleFileFrom($handleFile['file']->getFilename()).' | '.$handleFile['file']->getModule().' | '.$handleFile['file']->getName() ?></span>
                            <table class="dtt-table children" style="display:none">
                                <tr>
                                    <td>Filename</td>
                                    <td><?= $handleFile['file']->getFilename() ?></td>
                                </tr>
                                <tr>
                                    <td>Xml</td>
                                    <td class="xml"><?= $block->getHelperData()->formatNodeXmlToHtml($handleFile['xml']) ?></td>
                                </tr>
                            </table>
                        </li>
                        <?php endforeach ?>
                    </ul>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>

    <div id="dtt_tab_updates_xml<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-updates-xml xml">
        <?= $block->getHelperData()->formatNodeXmlToHtml($block->getUpdatesXml()) ?>
    </div>
</div>
