<?php
/* @var $block \Sga\DeveloperToolbar\Block\Toolbar\Request */
$request = $block->getRequest();
$website = $block->getWebsite();
$store = $block->getStore();
?>

<div class="dtt-tabs">
    <ul>
        <li class="dtt-tab" data-tab="#dtt_tab_request<?= $block->getRequestKey() ?>">Request</li>
        <li class="dtt-tab" data-tab="#dtt_tab_request_get<?= $block->getRequestKey() ?>">GET</li>
        <li class="dtt-tab" data-tab="#dtt_tab_request_post<?= $block->getRequestKey() ?>">POST</li>
        <li class="dtt-tab" data-tab="#dtt_tab_request_cookie<?= $block->getRequestKey() ?>">COOKIE</li>
    </ul>

    <div id="dtt_tab_request<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-request-request">
        <table class="dtt-table">
            <tr>
                <td>Website</td>
                <td><?= $website->getName().' / code : '.$website->getCode().' / id : '.$website->getId() ?></td>
            </tr>
            <tr>
                <td>Store</td>
                <td><?= $store->getName().' / code : '.$store->getCode().' / id : '.$store->getId() ?></td>
            </tr>
            <tr>
                <td>Module Name</td>
                <td><?= $request->getModuleName() ?></td>
            </tr>
            <tr>
                <td>Controller</td>
                <td><?= $request->getControllerName() ?></td>
            </tr>
            <tr>
                <td>Action</td>
                <td><?= $request->getActionName() ?></td>
            </tr>
            <tr>
                <td>Full Action</td>
                <td><?= $request->getFullActionName() ?></td>
            </tr>
            <tr>
                <td>Route</td>
                <td><?= $request->getRouteName() ?></td>
            </tr>
            <tr>
                <td>Area</td>
                <td><?= $block->getAppState()->getAreaCode() ?></td>
            </tr>
            <tr>
                <td>Magento Mode</td>
                <td><?= $block->getAppState()->getMode() ?></td>
            </tr>
            <tr>
                <td>Magento Version</td>
                <td><?= $block->getProductMetaData()->getVersion() ?></td>
            </tr>
            <tr>
                <td>Client IP</td>
                <td><?= $request->getClientIp() ?></td>
            </tr>
        </table>
    </div>

    <div id="dtt_tab_request_get<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-request-get">
        <table class="dtt-table">
        <?php if(count($_GET) > 0): ?>
            <?php foreach($_GET as $key => $value): ?>
            <tr>
                <td><?= $key ?></td>
                <td><pre><?php print_r($value) ?></pre></td>
            </tr>
            <?php endforeach ?>
        <?php else: ?>
            <tr>
                <td><?= __('No Data') ?></td>
            </tr>
        <?php endif ?>
        </table>
    </div>

    <div id="dtt_tab_request_post<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-request-post">
        <table class="dtt-table">
        <?php if(count($_POST) > 0): ?>
            <?php foreach($_POST as $key => $value): ?>
            <tr>
                <td><?= $key ?></td>
                <td><pre><?php print_r($value) ?></pre></td>
            </tr>
            <?php endforeach ?>
        <?php else: ?>
            <tr>
                <td><?= __('No Data') ?></td>
            </tr>
        <?php endif ?>
        </table>
    </div>

    <div id="dtt_tab_request_cookie<?= $block->getRequestKey() ?>" class="dtt-tab-container dtt-request-cookie">
        <table class="dtt-table">
        <?php if(count($_COOKIE) > 0): ?>
            <?php foreach($_COOKIE as $key => $value): ?>
            <tr>
                <td><?= $key ?></td>
                <td><pre><?php print_r($value) ?></pre></td>
            </tr>
            <?php endforeach ?>
        <?php else: ?>
            <tr>
                <td><?= __('No Data') ?></td>
            </tr>
        <?php endif ?>
        </table>
    </div>
</div>
