<?php /* @var $block \Sga\DeveloperToolbar\Block\Toolbar */ ?>
<?php
$requestKey = $block->getRequestKey();
$isShow = $block->isShow();

$config = [
    'requestKey' => $requestKey,
    'elements' => [
        'toolbar_prefix' => '#dtt',
        'item' => '.dtti',
        'item_id' => '#dtti_',
        'item_content' => '.dttic',
        'item_content_id' => '#dttic_',
        'close' => '.dttic-head .close'
    ],
    'cookiename' => \Sga\DeveloperToolbar\Helper\Data::COOKIE_NAME_DISPLAY
];
$children = $block->getChildren();
?>
<?php if (is_array($children) && count($children) > 0) : ?>
    <?= $block->getHtmlOtherRequests() ?>

    <div id="dtt<?= $requestKey ?>" class="dtt" data-key="<?= $requestKey ?>" style="<?= $isShow ? '' : 'display:none' ?>">
        <dl class="dtti-container">
            <?php foreach ($children as $child): ?>
                <?php if ($child->canDisplay()): ?>
                    <dt class="dtti dtti-<?= $child->getCode() ?> <?= $child->hasContent() ? 'dtti-has-content' : '' ?>" id="dtti_<?= $child->getCode() ?><?= $requestKey ?>" data-code="<?= $child->getCode() ?>"><?= $child->getLabel() ?></dt>

                    <?php if ($child->hasContent()): ?>
                        <dd class="dttic" id="dttic_<?= $child->getCode().$requestKey ?>" style="display:none;" data-code="<?= $child->getCode() ?>">
                            <div class="dttic-head"><a href="javascript:void(0)" class="close"><?= __('Close')?></a></div>
                            <div class="dttic-content"><div class="scroll"><?= $child->toHtml() ?></div></div>
                        </dd>
                    <?php endif ?>
                <?php endif ?>
            <?php endforeach ?>
        </dl>

        <script type="text/x-magento-init">
        {"#dtt<?= $requestKey ?>": {"Sga_DeveloperToolbar/js/toolbar": <?= $block->getJsonSerializer()->serialize($config) ?>}}
        </script>
    </div>
<?php endif ?>
